FROM python:3.9.1-slim-buster

# Don't use cached python packages
ENV PIP_NO_CACHE_DIR 1

# Add new fast source
RUN sed -i.bak 's/us-west-2\.ec2\.//' /etc/apt/sources.list

# Installing Required Packages
RUN apt update && \
    apt upgrade -y && \
    apt install --no-install-recommends -y \
    bash \
    python3-dev \
    python3-lxml \
    gcc \
    make \
    git

# Enter Workplace
WORKDIR /app/

# Copy folder
COPY . .

# Setup
RUN make dev-install